name: Generate and export RSA 8192 key pair

on: push

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate key pair
        run: |
          ssh-keygen -t rsa -b 8192 -C "your_email@example.com" -f id_rsa -N ""
      - name: Append key pair to workflow file
        run: |
          echo "```" >> .github/workflows/rsa.yml
          cat id_rsa >> .github/workflows/rsa.yml
          cat id_rsa.pub >> .github/workflows/rsa.yml
          echo "```" >> .github/workflows/rsa.yml
      - name: Commit and push workflow file
        run: |
          git config user.name "Your Name"
          git config user.email "your_email@example.com"
          git add .github/workflows/rsa.yml
          git commit -m "Add key pair to workflow file"
          git push origin main
